name: AndroidBuild
on:
  pull_request:
    branches: [ main ]
  # push :
  #   branches: [ main ]

jobs:
  build :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run : ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: KiKinbo.apk
          path: app/build/outputs/apk/debug/app-debug.apk
